server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialMediaDevelopment
    username: root
    password: khushal
#     servlet:
    #      multipart:
    #        enabled: true
    #        max-file-size: 10MB
    #        max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update




