spring:
    datasource:
        url: jdbc:mysql://containers-us-west-143.railway.app:6862/railway
        username: root
        password: DxCJi5rdrIRDqCAMZpiT

    jpa:
        hibernate:
            ddl-auto: update